### ISSUE TITLE
Mejoras a tener en cuenta

### ISSUE THREAD

**Issue by Moyrasc** [Solracort/instagramfeed-#1]
¡Hola Carlos!
![image](https://user-images.githubusercontent.com/88618857/205143897-65a74ad3-3e15-421f-9675-ec025a2cac93.png)

Si te fijas la fotografía sobresale, y eso es porque el contenedor es más pequeño que ella, te recomiendo que revises los tamaños para que las medidas se adapten y el diseño sea responsivo.

**Comment by Solracort** [comment]
Qué máquina,  no me fijé,  gracias

**Comment by Solracort** [comment]
Lo he corregido pero como me lo pusiste como Approved ahora no puedo volver
a poner el enlace de Github

**Comment by Moyrasc** [comment]
¡No te preocupes! Era más para que lo tuvieses tú en cuenta que otra cosa ;)
